// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanillaApi.Data;

#nullable disable

namespace PlanillaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240302164552_AddEntitiesEmpleadoAndContrato")]
    partial class AddEntitiesEmpleadoAndContrato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanillaApi.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ReportaAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportaAId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("PlanillaApi.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonificacion")
                        .HasColumnType("MONEY");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("MONEY");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PuestoId");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("PlanillaApi.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AfiliacionIGSS")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("AfiliacionIRTRA")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CUI")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .IsFixedLength();

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FechaAfiliacionIRTRA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .IsFixedLength();

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Pasaporte")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("PlanillaApi.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PlazasHabilitadas")
                        .HasColumnType("int");

                    b.Property<decimal>("TechoSalarial")
                        .HasColumnType("MONEY");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Puestos", (string)null);
                });

            modelBuilder.Entity("PlanillaApi.Entities.Area", b =>
                {
                    b.HasOne("PlanillaApi.Entities.Area", "ReportaA")
                        .WithMany("AreasSubordinadas")
                        .HasForeignKey("ReportaAId");

                    b.Navigation("ReportaA");
                });

            modelBuilder.Entity("PlanillaApi.Entities.Contrato", b =>
                {
                    b.HasOne("PlanillaApi.Entities.Empleado", "Empleado")
                        .WithMany("Contratos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanillaApi.Entities.Puesto", "Puesto")
                        .WithMany("Contratos")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("PlanillaApi.Entities.Puesto", b =>
                {
                    b.HasOne("PlanillaApi.Entities.Area", "Area")
                        .WithMany("Puestos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("PlanillaApi.Entities.Area", b =>
                {
                    b.Navigation("AreasSubordinadas");

                    b.Navigation("Puestos");
                });

            modelBuilder.Entity("PlanillaApi.Entities.Empleado", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("PlanillaApi.Entities.Puesto", b =>
                {
                    b.Navigation("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
