// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanillaApi.Data;

#nullable disable

namespace PlanillaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanillaApi.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ReportaAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportaAId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("PlanillaApi.Entities.Area", b =>
                {
                    b.HasOne("PlanillaApi.Entities.Area", "ReportaA")
                        .WithMany("AreasSubordinadas")
                        .HasForeignKey("ReportaAId");

                    b.Navigation("ReportaA");
                });

            modelBuilder.Entity("PlanillaApi.Entities.Area", b =>
                {
                    b.Navigation("AreasSubordinadas");
                });
#pragma warning restore 612, 618
        }
    }
}
